name: "Logi Pop Switch Bridge"
description: "A Bridge to trigger Home Assistant automations via Logitech POP buttons"
version: "0.0.8"
slug: "logi_pop_switches"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8400/tcp: 8400
host_dbus: true